### ISSUE TITLE
Question: Set Easing via RN Animated API

### ISSUE THREAD

**Issue by zachgibson** [react-community/lottie-react-native#267]
Is it possible to create a linear based animation in After Effects and then set the easing curve or spring via Animated API?

**Comment by cth0mas** [comment]
Of course, easing is nothing more than manipulation of the frame rate. I say of course with one caveat - you must use the imperative animation methodology to control the animation and provide the easing function you would like used to interpolate the frames.

**Comment by zachgibson** [comment]
@cth0mas Oh nice, I didn’t think about doing that. Why would one need to use the imperative way? Just specify easing via Animated.timing?

**Comment by cth0mas** [comment]
Yes exactly. Imperative animation in the scope of Lottie is controlling the progress of the total animation cycle from 0 to 1 using an Animated.Value, along with the range you simply set the easing function like any other Animated.timing call. I prefer imperative due to the ability to hook into loop cycles and kick off another loop if the situation calls for it.

I don't know about the latest version of Lottie, but I had to specify linear for all animations that looped or they would stutter due to the default easing.

I'll copy in some sample code when I have a chance.

**Comment by zachgibson** [comment]
@cth0mas I’ll try this and report back. I’m interested to see if linear AE animation with easing set via Animated will behave how I expect it to.

**Comment by cth0mas** [comment]
In my experience, Bodymovin converts AE frames to Lottie json, somewhere in there it does specify AE easings and if you use the play functionality of Lottie you will get the easing you exported, however - if you use imperative you are controlling the frame transition ease via Animated API.

**Comment by cth0mas** [comment]
@zachgibson here is a common scenario for my use of Lottie that I think will help your cause:

...

import animation from "../../lottie/animation.json";

//linear frame transitioning is needed as Animation.timing defaults to ease with imperative use
const linearEasing = t => t;

//Calculated animation duration for imperative use
calcDuration(source) {
    return source != null
      ? Math.round(source.op / source.fr * 1000)
      : 60;
  }
...
Play() {
// reset progess to 0 in case of looping function
this.state.animation.progress.setValue(0.0);

 Animated.timing(this.state.animation.progress, {
 to: 1.0,
 easing: linearEasing,
 duration: calcDuration(animation),
 useNativeDriver: true
 }).start(() => {
    //place callback logic here to loop animation or do other stuff after each animation cycle...
    if(shouldLoop)this.Play();
    if(shouldExist)this.PlayExit();
 });
}
