### ISSUE TITLE
Lottie React Native causing XCode Build Issues

### ISSUE THREAD

**Issue by jxshco** [react-community/lottie-react-native#391]
### Description

After updating XCode this morning to version 10.0 my project seems to be failing the build in XCode. It was working fine before so I'm not sure if something has happened to do with the update.

<img width="272" alt="screen shot 2018-10-06 at 16 47 33" src="https://user-images.githubusercontent.com/8502051/46573095-25b2a500-c988-11e8-9e8f-d543715b8180.png">

I have tried, re-installing Xcode, creating a fresh project and re-installing and re-linking everything but with no luck.

**Comment by andrewmarmion** [comment]
I am getting the same issues, though it only happened when I went from RN 0.56 -> 0.57

**Comment by duro** [comment]
Based on what I have read here: https://github.com/facebook/react-native/issues/21482

This has already been fixed in master. See https://github.com/react-community/lottie-react-native/pull/382

However, a new release has not been cut.

@emilioicai Can we get a new version cut? Since this repo builds code before publish, I can't just easily point my project at master without forking, and building the code.

**Comment by emilioicai** [comment]
@duro sure, you can expect a new version during this week
